### ISSUE TITLE
Create (basic) CONTRIBUTING.md file

### ISSUE THREAD

**Issue by sarelvdwalt** [afrihost/BaseCommandBundle#29]
It doesn't have to be amazing, it can merely be how to install it, and then run the tests to see if it works.

**Comment by sarelvdwalt** [comment]
For reference, this is the best practices according to github: https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by ibokg** [comment]
#31 Create basic contributing.md file
